# Generated by Django 5.2.17 on 2026-10-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('citizen', 'مستفيد'), ('director', 'مدير الشؤون الفنية'), ('technician', 'فني'), ('employee', 'موظف'), ('system_manager', 'مسؤول النظام'), ('secretariat', 'السكرتارية'), ('followup', 'قسم المتابعة'), ('finance', 'القسم المالي')], default='citizen', max_length=24),
        ),
    ]
