# Generated by Django 5.2.17 on 2026-10-05 20:42

import django.db.models.deletion
import portal.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.UUIDField()),
                ('payload_digest', models.CharField(max_length=64)),
                ('reporter_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('subscription_number', models.CharField(blank=True, max_length=50)),
                ('meter_number', models.CharField(blank=True, max_length=50)),
                ('complaint_type', models.CharField(choices=[('no_water', 'عدم وصول الماء للمشترك'), ('leak', 'وجود تسريب أو انكسار في أحد الخطوط'), ('illegal_connection', 'وجود ربط مخالف'), ('water_quality', 'وجود طعم أو لون متغير للماء'), ('high_bill', 'المبلغ مرتفع في الفاتورة'), ('weak_water', 'الماء ضعيف'), ('other', 'أخرى')], max_length=32)),
                ('other_type', models.CharField(blank=True, max_length=150)),
                ('neighborhood', models.CharField(choices=[('n01', 'المجمع (إدارة الأمن)'), ('n02', 'المجمع (سوق القات القديم)'), ('n03', 'المجمع (المؤسسة)'), ('n04', 'المجمع (الحديقة القديم)'), ('n05', 'المجمع (المستشفى العسكري)'), ('n06', 'حي الجامعة'), ('n07', 'الحويضنة'), ('n08', 'حي السلام (الزراعة)'), ('n09', 'حي الشركة (الصحن)'), ('n10', 'حي الشركة (الصيانة)'), ('n11', 'حي الروضة'), ('n12', 'الروضة (نخلا)'), ('n13', 'حي الصحن (القادسية)'), ('n14', 'حي البقائل (التوفيق)'), ('n15', 'حي المغاوير'), ('n16', 'حي النبلاء'), ('n17', 'حي الخير'), ('n18', 'حارة الهدى'), ('n19', 'حي الجزيرة'), ('n20', 'حي النور'), ('n21', 'حي الصيانة'), ('n22', 'حي الأمن السياسي'), ('n23', 'حي النصر'), ('n24', 'حي مجمع الخير الصيانة'), ('n25', 'حي مجمع الخير'), ('n26', 'حي الرضوان'), ('n27', 'الجفينة – القطاع 1'), ('n28', 'الجفينة – القطاع 2'), ('n29', 'الجفينة – القطاع 3'), ('n30', 'الجفينة – القطاع 4'), ('n31', 'الجفينة – القطاع 5'), ('n32', 'الجفينة – القطاع 6'), ('n33', 'الجفينة – القطاع 7'), ('n34', 'الجفينة – القطاع 8'), ('n35', 'الجفينة – القطاع 9'), ('n36', 'الجفينة – القطاع 10'), ('other', 'أخرى')], max_length=16)),
                ('other_neighborhood', models.CharField(blank=True, max_length=150)),
                ('address', models.CharField(max_length=500)),
                ('landmark', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=5000)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('received', 'تم الاستلام')], default='received', max_length=24)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=portal.models.complaint_photo_path)),
                ('position', models.PositiveSmallIntegerField()),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='portal.complaint')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddConstraint(
            model_name='complaint',
            constraint=models.UniqueConstraint(fields=('owner', 'client_id'), name='unique_owner_complaint'),
        ),
        migrations.AddConstraint(
            model_name='complaintphoto',
            constraint=models.UniqueConstraint(fields=('complaint', 'position'), name='unique_complaint_photo_position'),
        ),
    ]
