# Generated by Django 5.2.17 on 2026-10-06 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def route_existing(apps, schema_editor):
    Complaint = apps.get_model('portal', 'Complaint')
    Complaint.objects.filter(complaint_type='high_bill').update(department='finance')


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_complaint_complaintphoto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complaint',
            name='department',
            field=models.CharField(choices=[('technical', 'الشؤون الفنية'), ('finance', 'القسم المالي')], default='technical', max_length=16),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('received', 'تم الاستلام'), ('assigned', 'أُسند إلى المختص'), ('in_progress', 'قيد المعالجة'), ('review', 'بانتظار مراجعة المدير'), ('returned', 'أُعيد للمعالجة'), ('closed', 'مغلق')], default='received', max_length=24),
        ),
        migrations.CreateModel(
            name='ComplaintEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=24)),
                ('note', models.TextField(blank=True, max_length=3000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='complaint_actions', to=settings.AUTH_USER_MODEL)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='portal.complaint')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.RunPython(route_existing, migrations.RunPython.noop),
    ]
