# Generated by Django 5.2.17 on 2026-10-06 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_complaint_assignee_complaint_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.UUIDField()),
                ('payload_digest', models.CharField(max_length=64)),
                ('person_name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=500)),
                ('area', models.CharField(max_length=150)),
                ('estimated_cubic_meters', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estimate_days', models.PositiveSmallIntegerField()),
                ('activity', models.CharField(choices=[('residential', 'منزلي'), ('commercial', 'تجاري'), ('government', 'حكومي')], max_length=20)),
                ('kind', models.CharField(choices=[('random_connection', 'ربط عشوائي'), ('illegal_subscription', 'اشتراك مخالف')], max_length=24)),
                ('description', models.TextField(blank=True, max_length=3000)),
                ('status', models.CharField(choices=[('system_manager', 'لدى مسؤول النظام'), ('secretariat', 'لدى السكرتارية'), ('followup', 'لدى قسم المتابعة'), ('results_returned', 'عادت النتائج للفنية والمالية')], default='system_manager', max_length=24)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_violations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='ViolationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=32)),
                ('note', models.TextField(blank=True, max_length=3000)),
                ('recipient', models.CharField(blank=True, max_length=200)),
                ('document_reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='violation_actions', to=settings.AUTH_USER_MODEL)),
                ('violation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='portal.violation')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='violation',
            constraint=models.UniqueConstraint(fields=('reporter', 'client_id'), name='unique_reporter_violation'),
        ),
    ]
