# Generated by Django 5.2.17 on 2026-10-06 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_violation_violationevent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violation',
            name='status',
            field=models.CharField(choices=[('system_manager', 'لدى مسؤول النظام'), ('secretariat', 'لدى السكرتارية'), ('followup', 'لدى قسم المتابعة'), ('results_returned', 'عادت النتائج للفنية والمالية'), ('awaiting_payment', 'بانتظار السداد'), ('paid', 'أكدت المالية السداد'), ('closed', 'مغلقة بعد التسوية')], default='system_manager', max_length=24),
        ),
        migrations.CreateModel(
            name='ViolationSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_code', models.CharField(max_length=64)),
                ('fixed_fee', models.DecimalField(decimal_places=2, max_digits=16)),
                ('unit_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('approved_units', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_description', models.CharField(max_length=100)),
                ('assessment_basis', models.TextField(max_length=3000)),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('payment_receipt', models.CharField(blank=True, max_length=100)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('closure_note', models.TextField(blank=True, max_length=3000)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('assessed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='violation_assessments', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_violations', to=settings.AUTH_USER_MODEL)),
                ('payment_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='violation_payments', to=settings.AUTH_USER_MODEL)),
                ('violation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settlement', to='portal.violation')),
            ],
        ),
    ]
