# Generated by Django 5.2.17 on 2026-10-06 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_alter_violation_status_violationsettlement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViolationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.UUIDField()),
                ('kind', models.CharField(choices=[('minutes', 'محضر معاينة'), ('letter', 'مذكرة أو مراسلة')], max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('official_number', models.CharField(blank=True, max_length=100)),
                ('document_date', models.DateField()),
                ('recipient', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(max_length=12000)),
                ('status', models.CharField(choices=[('draft', 'مسودة للتحرير'), ('issued', 'صادرة من النظام')], default='draft', max_length=16)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_violation_documents', to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issued_violation_documents', to=settings.AUTH_USER_MODEL)),
                ('violation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='portal.violation')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'constraints': [models.UniqueConstraint(fields=('violation', 'client_id'), name='unique_violation_document_request')],
            },
        ),
    ]
