# Generated by Django 5.2.17 on 2026-10-06 07:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_violationdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.UUIDField(default=uuid.uuid4)),
                ('source', models.CharField(choices=[('violation', 'ملف مخالفة'), ('complaint', 'بلاغ مستفيد'), ('summary', 'تقرير إداري مجمع')], max_length=16)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_templates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportTemplateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.UUIDField(default=uuid.uuid4)),
                ('number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=160)),
                ('spec', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_template_versions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='template_versions', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='portal.reporttemplate')),
            ],
            options={
                'ordering': ['-number', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplateEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_template_events', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='portal.reporttemplate')),
                ('version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='portal.reporttemplateversion')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='active_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='portal.reporttemplateversion'),
        ),
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.UUIDField()),
                ('payload_digest', models.CharField(max_length=64)),
                ('content', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_reports', to='portal.complaint')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saved_reports', to=settings.AUTH_USER_MODEL)),
                ('template_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saved_reports', to='portal.reporttemplateversion')),
                ('violation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_reports', to='portal.violation')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='reporttemplateversion',
            constraint=models.UniqueConstraint(fields=('template', 'number'), name='unique_report_template_version'),
        ),
        migrations.AddConstraint(
            model_name='reporttemplateversion',
            constraint=models.UniqueConstraint(fields=('template', 'client_id'), name='unique_template_edit_request'),
        ),
        migrations.AddConstraint(
            model_name='reporttemplate',
            constraint=models.UniqueConstraint(fields=('created_by', 'client_id'), name='unique_template_create_request'),
        ),
        migrations.AddConstraint(
            model_name='savedreport',
            constraint=models.UniqueConstraint(fields=('created_by', 'client_id'), name='unique_saved_report_request'),
        ),
        migrations.AddConstraint(
            model_name='savedreport',
            constraint=models.CheckConstraint(condition=models.Q(('complaint__isnull', True), ('violation__isnull', True), _connector='OR'), name='one_saved_report_record'),
        ),
    ]
