# Generated by Django 5.2.17 on 2026-10-07 08:16

import django.db.models.deletion
import portal.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_reporttemplate_reporttemplateversion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginThrottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('window_start', models.DateTimeField()),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='accountevent',
            name='new_role',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='accountevent',
            name='note',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='accountevent',
            name='previous_role',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='complaintevent',
            name='new_assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='new_complaint_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complaintevent',
            name='previous_assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='previous_complaint_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='is_department_responsible',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ComplaintExecutionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.UUIDField()),
                ('payload_digest', models.CharField(max_length=64)),
                ('assignment_event_id', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execution_results', to=settings.AUTH_USER_MODEL)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_results', to='portal.complaint')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='execution_result', to='portal.complaintevent')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintExecutionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=portal.models.execution_photo_path)),
                ('position', models.PositiveSmallIntegerField()),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='portal.complaintexecutionresult')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddConstraint(
            model_name='complaintexecutionresult',
            constraint=models.UniqueConstraint(fields=('actor', 'client_id'), name='unique_actor_execution_result'),
        ),
        migrations.AddConstraint(
            model_name='complaintexecutionphoto',
            constraint=models.UniqueConstraint(fields=('result', 'position'), name='unique_result_photo_position'),
        ),
    ]
